use_frameworks!

target 'NSelect_Example' do
  pod 'NSelect', :path => '../'

  target 'NSelect_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    
    pod 'UIRadioButton', :path => '/Users/iOSDev/Clones/UIRadioButton'

  end
end
