use_frameworks!

target 'NSelect_Example' do
 
  pod 'UIRadioButton', :git => 'https://github.com/fitsyu/UIRadioButton.git'
  pod 'NSelect', :path => '../'

  target 'NSelect_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    

  end
end
